name: minti_dbt
version: 1.0.0
config-version: 2

profile: minti_dbt

model-paths:
  - models
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  minti_dbt:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: marts
    marts:
      +materialized: table
      +schema: marts
